import React, { useState, useEffect } from 'react';
import { Loader, Card, FormField } from '../components';
import axios from 'axios';

const RenderCards = ({ data, title}) => {
  if(data && data.length > 0) {
    return data.map((post) => <Card key={post._id} />)
  }
  return <h2 className="mt-5 font-bold text-blue-600 text-xl uppercase">{title}</h2>;
}

function Home() {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState('');

  useEffect(() => {
    const fetchData = async () => {
      setLoading(true);
      try {
        const response = await axios.get('/api/posts');
        setAllPosts(response.data);
      } catch (error) {
        console.error(error);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  const handleSearch = (event) => {
    event.preventDefault();
    setSearchText(event.target.value);
  };

  return (
    <section className="max-w-7xl mx-auto" style={{ marginTop: "0", textSizeAdjust: "100%" }}>

      <div>
        <h1 className="font-extrabold text-black text-2xl">The Community Showcase</h1>
        <p className="mt-2 text-gray-700 text-14 max-w-500">
          Browse through a collection of imaginative and visually stunning images generated by DALL-E AI
        </p>
      </div>
      <div className="mt-16">
        <FormField handleSearch={handleSearch} />
      </div>
      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-gray-700 text-xl mb-3">
                Showing results for <span className="text-black">{searchText}</span>
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards
                  data={[]}
                  title="No search results found" />
              ) : (
                <RenderCards
                  data={allPosts}
                  title="No posts found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
}

export default Home;
